version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: data_project_postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: olist_dw
    ports:
      - "5432:5432"
    volumes:
      - ./data:/data   # <-- monta sua pasta local 'data' dentro do container
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: